### ISSUE TITLE
Images for Readme

### ISSUE THREAD

**Issue by rezazad68** [rezazad68/Dynamic-3D-Action-Recognition-on-RGB-D-Videos#1]
![action_hand](https://user-images.githubusercontent.com/20574689/29744825-1f43af08-8ac2-11e7-894e-2cb1b316185a.png)

**Comment by Kerrwy** [comment]
Question about codes in Description_Classification： there is a clearly error in "Eigen_Vector(:,t)=V(:,index(p));" , they do not have same size.
And I do not find a full paper from google, so whether your paper had been made public, how can I find it？

**Comment by alaa137** [comment]
I get an error when running Main_MSRAction3D.m:

> Error using load
> Unable to read file 'Action3D_Features'. No such file or directory.
> 
> Error in Step2_Description_Classification (line 7)
> load Action3D_Features
> 
> Error in Main_MSRAction3D (line 31)
>     Step2_Description_Classification

**Comment by rezazad68** [comment]
Hi,
All errors fixed now. Thanks for the feedback.

**Comment by luyaozhi** [comment]
> 关于Description_Classification中的代码的问题：“Eigen_Vector（：，t）= V（：，index（p））;”中存在明显的错误。，它们没有相同的尺寸。
> 我没有找到谷歌的完整论文，所以你的论文是否公开，我怎么能找到它？

When I used the MSR Gesture 3D database, there was the same mistake. Did you solve it?

**Comment by rezazad68** [comment]
The problem is fixed now. The uploaded dataset in this repository was not complete, but now it is fixed. redownload the code and run it for MSR Action 3D. It should be work for MSR Gesture 3D too.

**Comment by luyaozhi** [comment]
> The problem is fixed now. The uploaded dataset in this repository was not complete, but now it is fixed. redownload the code and run it for MSR Action 3D. It should be work for MSR Gesture 3D too.

Thank you . When I download and run the MSR Action 3D dataset again, it works. But when I download the MSR Gesture 3D dataset, there are errors in data sub_depth_08_13.mat，sub_depth_08_14.mat andsub_depth_08_15.mat（they are 2kb）. 
After deleting these three data, there is still this error in the Description_Classification.

Description_Classification/Find_K_Max_Eigen (line 251)
          Eigen_Vector(:,t)=V(:,index(p));

Because p is 0 at this time, and the error prompt subscript index must be a positive integer type or logical type.

 Can you help me solve it?thank you very much.

**Comment by preksha12** [comment]
I am not able to download NTU RGBD code. Can you share actual code?
